// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Accounter is an autogenerated mock type for the Accounter type
type Accounter struct {
	mock.Mock
}

// AddAccount provides a mock function with given fields: accountID, adminRoleARN
func (_m *Accounter) AddAccount(accountID string, adminRoleARN string) {
	_m.Called(accountID, adminRoleARN)
}

// GetAccount provides a mock function with given fields: accountID
func (_m *Accounter) GetAccount(accountID string) {
	_m.Called(accountID)
}

// ListAccounts provides a mock function with given fields:
func (_m *Accounter) ListAccounts() {
	_m.Called()
}

// RemoveAccount provides a mock function with given fields: accountID
func (_m *Accounter) RemoveAccount(accountID string) {
	_m.Called(accountID)
}

// NewAccounter creates a new instance of Accounter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAccounter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Accounter {
	mock := &Accounter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
