// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Authenticater is an autogenerated mock type for the Authenticater type
type Authenticater struct {
	mock.Mock
}

// Authenticate provides a mock function with given fields:
func (_m *Authenticater) Authenticate() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthenticater creates a new instance of Authenticater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthenticater(t interface {
	mock.TestingT
	Cleanup(func())
}) *Authenticater {
	mock := &Authenticater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
