// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import (
	fs "io/fs"
	os "os"

	mock "github.com/stretchr/testify/mock"
)

// FileSystemer is an autogenerated mock type for the FileSystemer type
type FileSystemer struct {
	mock.Mock
}

// ChToConfigDir provides a mock function with given fields:
func (_m *FileSystemer) ChToConfigDir() (string, string) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChToConfigDir")
	}

	var r0 string
	var r1 string
	if rf, ok := ret.Get(0).(func() (string, string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// ChToTmpDir provides a mock function with given fields:
func (_m *FileSystemer) ChToTmpDir() (string, string) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ChToTmpDir")
	}

	var r0 string
	var r1 string
	if rf, ok := ret.Get(0).(func() (string, string)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func() string); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(string)
	}

	return r0, r1
}

// Chdir provides a mock function with given fields: path
func (_m *FileSystemer) Chdir(path string) {
	_m.Called(path)
}

// CreateConfigDirTree provides a mock function with given fields: dceVersion
func (_m *FileSystemer) CreateConfigDirTree(dceVersion string) error {
	ret := _m.Called(dceVersion)

	if len(ret) == 0 {
		panic("no return value specified for CreateConfigDirTree")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(dceVersion)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetArtifactsDir provides a mock function with given fields: dceVersion
func (_m *FileSystemer) GetArtifactsDir(dceVersion string) string {
	ret := _m.Called(dceVersion)

	if len(ret) == 0 {
		panic("no return value specified for GetArtifactsDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(dceVersion)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetCacheDir provides a mock function with given fields:
func (_m *FileSystemer) GetCacheDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCacheDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetConfigDir provides a mock function with given fields:
func (_m *FileSystemer) GetConfigDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetConfigFile provides a mock function with given fields:
func (_m *FileSystemer) GetConfigFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetHomeDir provides a mock function with given fields:
func (_m *FileSystemer) GetHomeDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetHomeDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLocalMainTFFile provides a mock function with given fields:
func (_m *FileSystemer) GetLocalMainTFFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocalMainTFFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLocalTFModuleDir provides a mock function with given fields:
func (_m *FileSystemer) GetLocalTFModuleDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLocalTFModuleDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetLogFile provides a mock function with given fields:
func (_m *FileSystemer) GetLogFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLogFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTerraformBin provides a mock function with given fields:
func (_m *FileSystemer) GetTerraformBin() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformBin")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTerraformBinDir provides a mock function with given fields:
func (_m *FileSystemer) GetTerraformBinDir() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformBinDir")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetTerraformStateFile provides a mock function with given fields:
func (_m *FileSystemer) GetTerraformStateFile() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTerraformStateFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// IsExistingFile provides a mock function with given fields: path
func (_m *FileSystemer) IsExistingFile(path string) bool {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for IsExistingFile")
	}

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OpenFileWriter provides a mock function with given fields: path
func (_m *FileSystemer) OpenFileWriter(path string) (*os.File, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for OpenFileWriter")
	}

	var r0 *os.File
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*os.File, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) *os.File); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.File)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadDir provides a mock function with given fields: path
func (_m *FileSystemer) ReadDir(path string) []fs.FileInfo {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadDir")
	}

	var r0 []fs.FileInfo
	if rf, ok := ret.Get(0).(func(string) []fs.FileInfo); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fs.FileInfo)
		}
	}

	return r0
}

// ReadFromFile provides a mock function with given fields: path
func (_m *FileSystemer) ReadFromFile(path string) string {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for ReadFromFile")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(path)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// ReadInConfig provides a mock function with given fields:
func (_m *FileSystemer) ReadInConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadInConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveAll provides a mock function with given fields: path
func (_m *FileSystemer) RemoveAll(path string) {
	_m.Called(path)
}

// Unarchive provides a mock function with given fields: source, destination
func (_m *FileSystemer) Unarchive(source string, destination string) error {
	ret := _m.Called(source, destination)

	if len(ret) == 0 {
		panic("no return value specified for Unarchive")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(source, destination)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteConfig provides a mock function with given fields:
func (_m *FileSystemer) WriteConfig() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WriteConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteFile provides a mock function with given fields: fileName, data
func (_m *FileSystemer) WriteFile(fileName string, data string) {
	_m.Called(fileName, data)
}

// NewFileSystemer creates a new instance of FileSystemer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileSystemer(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileSystemer {
	mock := &FileSystemer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
