// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Initer is an autogenerated mock type for the Initer type
type Initer struct {
	mock.Mock
}

// InitializeDCE provides a mock function with given fields:
func (_m *Initer) InitializeDCE() {
	_m.Called()
}

// NewIniter creates a new instance of Initer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIniter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Initer {
	mock := &Initer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
