// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TerraformBinDownloader is an autogenerated mock type for the TerraformBinDownloader type
type TerraformBinDownloader struct {
	mock.Mock
}

// Download provides a mock function with given fields: url, localpath
func (_m *TerraformBinDownloader) Download(url string, localpath string) error {
	ret := _m.Called(url, localpath)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(url, localpath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTerraformBinDownloader creates a new instance of TerraformBinDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTerraformBinDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *TerraformBinDownloader {
	mock := &TerraformBinDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
