// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Usager is an autogenerated mock type for the Usager type
type Usager struct {
	mock.Mock
}

// GetUsage provides a mock function with given fields: startDate, endDate
func (_m *Usager) GetUsage(startDate float64, endDate float64) {
	_m.Called(startDate, endDate)
}

// NewUsager creates a new instance of Usager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsager(t interface {
	mock.TestingT
	Cleanup(func())
}) *Usager {
	mock := &Usager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
