// Code generated by mockery v2.45.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Weber is an autogenerated mock type for the Weber type
type Weber struct {
	mock.Mock
}

// OpenURL provides a mock function with given fields: url
func (_m *Weber) OpenURL(url string) {
	_m.Called(url)
}

// NewWeber creates a new instance of Weber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWeber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Weber {
	mock := &Weber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
