// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OptionsAuthReader is a Reader for the OptionsAuth structure.
type OptionsAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionsAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionsAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[OPTIONS /auth] OptionsAuth", response, response.Code())
	}
}

// NewOptionsAuthOK creates a OptionsAuthOK with default headers values
func NewOptionsAuthOK() *OptionsAuthOK {
	return &OptionsAuthOK{}
}

/*
OptionsAuthOK describes a response with status code 200, with default header values.

Default response for CORS method
*/
type OptionsAuthOK struct {
	AccessControlAllowHeaders string
	AccessControlAllowMethods string
	AccessControlAllowOrigin  string
}

// IsSuccess returns true when this options auth o k response has a 2xx status code
func (o *OptionsAuthOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this options auth o k response has a 3xx status code
func (o *OptionsAuthOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this options auth o k response has a 4xx status code
func (o *OptionsAuthOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this options auth o k response has a 5xx status code
func (o *OptionsAuthOK) IsServerError() bool {
	return false
}

// IsCode returns true when this options auth o k response a status code equal to that given
func (o *OptionsAuthOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the options auth o k response
func (o *OptionsAuthOK) Code() int {
	return 200
}

func (o *OptionsAuthOK) Error() string {
	return fmt.Sprintf("[OPTIONS /auth][%d] optionsAuthOK", 200)
}

func (o *OptionsAuthOK) String() string {
	return fmt.Sprintf("[OPTIONS /auth][%d] optionsAuthOK", 200)
}

func (o *OptionsAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Access-Control-Allow-Headers
	hdrAccessControlAllowHeaders := response.GetHeader("Access-Control-Allow-Headers")

	if hdrAccessControlAllowHeaders != "" {
		o.AccessControlAllowHeaders = hdrAccessControlAllowHeaders
	}

	// hydrates response header Access-Control-Allow-Methods
	hdrAccessControlAllowMethods := response.GetHeader("Access-Control-Allow-Methods")

	if hdrAccessControlAllowMethods != "" {
		o.AccessControlAllowMethods = hdrAccessControlAllowMethods
	}

	// hydrates response header Access-Control-Allow-Origin
	hdrAccessControlAllowOrigin := response.GetHeader("Access-Control-Allow-Origin")

	if hdrAccessControlAllowOrigin != "" {
		o.AccessControlAllowOrigin = hdrAccessControlAllowOrigin
	}

	return nil
}
