// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OptionsAccountsIDReader is a Reader for the OptionsAccountsID structure.
type OptionsAccountsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionsAccountsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionsAccountsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[OPTIONS /accounts/{id}] OptionsAccountsID", response, response.Code())
	}
}

// NewOptionsAccountsIDOK creates a OptionsAccountsIDOK with default headers values
func NewOptionsAccountsIDOK() *OptionsAccountsIDOK {
	return &OptionsAccountsIDOK{}
}

/*
OptionsAccountsIDOK describes a response with status code 200, with default header values.

Default response for CORS method
*/
type OptionsAccountsIDOK struct {
	AccessControlAllowHeaders string
	AccessControlAllowMethods string
	AccessControlAllowOrigin  string
}

// IsSuccess returns true when this options accounts Id o k response has a 2xx status code
func (o *OptionsAccountsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this options accounts Id o k response has a 3xx status code
func (o *OptionsAccountsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this options accounts Id o k response has a 4xx status code
func (o *OptionsAccountsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this options accounts Id o k response has a 5xx status code
func (o *OptionsAccountsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this options accounts Id o k response a status code equal to that given
func (o *OptionsAccountsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the options accounts Id o k response
func (o *OptionsAccountsIDOK) Code() int {
	return 200
}

func (o *OptionsAccountsIDOK) Error() string {
	return fmt.Sprintf("[OPTIONS /accounts/{id}][%d] optionsAccountsIdOK", 200)
}

func (o *OptionsAccountsIDOK) String() string {
	return fmt.Sprintf("[OPTIONS /accounts/{id}][%d] optionsAccountsIdOK", 200)
}

func (o *OptionsAccountsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Access-Control-Allow-Headers
	hdrAccessControlAllowHeaders := response.GetHeader("Access-Control-Allow-Headers")

	if hdrAccessControlAllowHeaders != "" {
		o.AccessControlAllowHeaders = hdrAccessControlAllowHeaders
	}

	// hydrates response header Access-Control-Allow-Methods
	hdrAccessControlAllowMethods := response.GetHeader("Access-Control-Allow-Methods")

	if hdrAccessControlAllowMethods != "" {
		o.AccessControlAllowMethods = hdrAccessControlAllowMethods
	}

	// hydrates response header Access-Control-Allow-Origin
	hdrAccessControlAllowOrigin := response.GetHeader("Access-Control-Allow-Origin")

	if hdrAccessControlAllowOrigin != "" {
		o.AccessControlAllowOrigin = hdrAccessControlAllowOrigin
	}

	return nil
}
