// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewOptionsLeasesIDParams creates a new OptionsLeasesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewOptionsLeasesIDParams() *OptionsLeasesIDParams {
	return &OptionsLeasesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewOptionsLeasesIDParamsWithTimeout creates a new OptionsLeasesIDParams object
// with the ability to set a timeout on a request.
func NewOptionsLeasesIDParamsWithTimeout(timeout time.Duration) *OptionsLeasesIDParams {
	return &OptionsLeasesIDParams{
		timeout: timeout,
	}
}

// NewOptionsLeasesIDParamsWithContext creates a new OptionsLeasesIDParams object
// with the ability to set a context for a request.
func NewOptionsLeasesIDParamsWithContext(ctx context.Context) *OptionsLeasesIDParams {
	return &OptionsLeasesIDParams{
		Context: ctx,
	}
}

// NewOptionsLeasesIDParamsWithHTTPClient creates a new OptionsLeasesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewOptionsLeasesIDParamsWithHTTPClient(client *http.Client) *OptionsLeasesIDParams {
	return &OptionsLeasesIDParams{
		HTTPClient: client,
	}
}

/*
OptionsLeasesIDParams contains all the parameters to send to the API endpoint

	for the options leases ID operation.

	Typically these are written to a http.Request.
*/
type OptionsLeasesIDParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the options leases ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsLeasesIDParams) WithDefaults() *OptionsLeasesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the options leases ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *OptionsLeasesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the options leases ID params
func (o *OptionsLeasesIDParams) WithTimeout(timeout time.Duration) *OptionsLeasesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the options leases ID params
func (o *OptionsLeasesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the options leases ID params
func (o *OptionsLeasesIDParams) WithContext(ctx context.Context) *OptionsLeasesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the options leases ID params
func (o *OptionsLeasesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the options leases ID params
func (o *OptionsLeasesIDParams) WithHTTPClient(client *http.Client) *OptionsLeasesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the options leases ID params
func (o *OptionsLeasesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *OptionsLeasesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
