// Code generated by go-swagger; DO NOT EDIT.

package c_o_r_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// OptionsLeasesReader is a Reader for the OptionsLeases structure.
type OptionsLeasesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *OptionsLeasesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewOptionsLeasesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[OPTIONS /leases] OptionsLeases", response, response.Code())
	}
}

// NewOptionsLeasesOK creates a OptionsLeasesOK with default headers values
func NewOptionsLeasesOK() *OptionsLeasesOK {
	return &OptionsLeasesOK{}
}

/*
OptionsLeasesOK describes a response with status code 200, with default header values.

Default response for CORS method
*/
type OptionsLeasesOK struct {
	AccessControlAllowHeaders string
	AccessControlAllowMethods string
	AccessControlAllowOrigin  string
}

// IsSuccess returns true when this options leases o k response has a 2xx status code
func (o *OptionsLeasesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this options leases o k response has a 3xx status code
func (o *OptionsLeasesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this options leases o k response has a 4xx status code
func (o *OptionsLeasesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this options leases o k response has a 5xx status code
func (o *OptionsLeasesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this options leases o k response a status code equal to that given
func (o *OptionsLeasesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the options leases o k response
func (o *OptionsLeasesOK) Code() int {
	return 200
}

func (o *OptionsLeasesOK) Error() string {
	return fmt.Sprintf("[OPTIONS /leases][%d] optionsLeasesOK", 200)
}

func (o *OptionsLeasesOK) String() string {
	return fmt.Sprintf("[OPTIONS /leases][%d] optionsLeasesOK", 200)
}

func (o *OptionsLeasesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Access-Control-Allow-Headers
	hdrAccessControlAllowHeaders := response.GetHeader("Access-Control-Allow-Headers")

	if hdrAccessControlAllowHeaders != "" {
		o.AccessControlAllowHeaders = hdrAccessControlAllowHeaders
	}

	// hydrates response header Access-Control-Allow-Methods
	hdrAccessControlAllowMethods := response.GetHeader("Access-Control-Allow-Methods")

	if hdrAccessControlAllowMethods != "" {
		o.AccessControlAllowMethods = hdrAccessControlAllowMethods
	}

	// hydrates response header Access-Control-Allow-Origin
	hdrAccessControlAllowOrigin := response.GetHeader("Access-Control-Allow-Origin")

	if hdrAccessControlAllowOrigin != "" {
		o.AccessControlAllowOrigin = hdrAccessControlAllowOrigin
	}

	return nil
}
