// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteLeasesParams creates a new DeleteLeasesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteLeasesParams() *DeleteLeasesParams {
	return &DeleteLeasesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteLeasesParamsWithTimeout creates a new DeleteLeasesParams object
// with the ability to set a timeout on a request.
func NewDeleteLeasesParamsWithTimeout(timeout time.Duration) *DeleteLeasesParams {
	return &DeleteLeasesParams{
		timeout: timeout,
	}
}

// NewDeleteLeasesParamsWithContext creates a new DeleteLeasesParams object
// with the ability to set a context for a request.
func NewDeleteLeasesParamsWithContext(ctx context.Context) *DeleteLeasesParams {
	return &DeleteLeasesParams{
		Context: ctx,
	}
}

// NewDeleteLeasesParamsWithHTTPClient creates a new DeleteLeasesParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteLeasesParamsWithHTTPClient(client *http.Client) *DeleteLeasesParams {
	return &DeleteLeasesParams{
		HTTPClient: client,
	}
}

/*
DeleteLeasesParams contains all the parameters to send to the API endpoint

	for the delete leases operation.

	Typically these are written to a http.Request.
*/
type DeleteLeasesParams struct {

	/* Lease.

	   The owner of the lease
	*/
	Lease DeleteLeasesBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLeasesParams) WithDefaults() *DeleteLeasesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete leases params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteLeasesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete leases params
func (o *DeleteLeasesParams) WithTimeout(timeout time.Duration) *DeleteLeasesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete leases params
func (o *DeleteLeasesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete leases params
func (o *DeleteLeasesParams) WithContext(ctx context.Context) *DeleteLeasesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete leases params
func (o *DeleteLeasesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete leases params
func (o *DeleteLeasesParams) WithHTTPClient(client *http.Client) *DeleteLeasesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete leases params
func (o *DeleteLeasesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLease adds the lease to the delete leases params
func (o *DeleteLeasesParams) WithLease(lease DeleteLeasesBody) *DeleteLeasesParams {
	o.SetLease(lease)
	return o
}

// SetLease adds the lease to the delete leases params
func (o *DeleteLeasesParams) SetLease(lease DeleteLeasesBody) {
	o.Lease = lease
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteLeasesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Lease); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
