// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAuthFileReader is a Reader for the GetAuthFile structure.
type GetAuthFileReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAuthFileReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAuthFileOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /auth/{file+}] GetAuthFile", response, response.Code())
	}
}

// NewGetAuthFileOK creates a GetAuthFileOK with default headers values
func NewGetAuthFileOK() *GetAuthFileOK {
	return &GetAuthFileOK{}
}

/*
GetAuthFileOK describes a response with status code 200, with default header values.

GetAuthFileOK get auth file o k
*/
type GetAuthFileOK struct {
	AccessControlAllowHeaders string
	AccessControlAllowMethods string
	AccessControlAllowOrigin  string

	Payload interface{}
}

// IsSuccess returns true when this get auth file o k response has a 2xx status code
func (o *GetAuthFileOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get auth file o k response has a 3xx status code
func (o *GetAuthFileOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get auth file o k response has a 4xx status code
func (o *GetAuthFileOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get auth file o k response has a 5xx status code
func (o *GetAuthFileOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get auth file o k response a status code equal to that given
func (o *GetAuthFileOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get auth file o k response
func (o *GetAuthFileOK) Code() int {
	return 200
}

func (o *GetAuthFileOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{file+}][%d] getAuthFileOK %s", 200, payload)
}

func (o *GetAuthFileOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/{file+}][%d] getAuthFileOK %s", 200, payload)
}

func (o *GetAuthFileOK) GetPayload() interface{} {
	return o.Payload
}

func (o *GetAuthFileOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Access-Control-Allow-Headers
	hdrAccessControlAllowHeaders := response.GetHeader("Access-Control-Allow-Headers")

	if hdrAccessControlAllowHeaders != "" {
		o.AccessControlAllowHeaders = hdrAccessControlAllowHeaders
	}

	// hydrates response header Access-Control-Allow-Methods
	hdrAccessControlAllowMethods := response.GetHeader("Access-Control-Allow-Methods")

	if hdrAccessControlAllowMethods != "" {
		o.AccessControlAllowMethods = hdrAccessControlAllowMethods
	}

	// hydrates response header Access-Control-Allow-Origin
	hdrAccessControlAllowOrigin := response.GetHeader("Access-Control-Allow-Origin")

	if hdrAccessControlAllowOrigin != "" {
		o.AccessControlAllowOrigin = hdrAccessControlAllowOrigin
	}

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
