// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetAccountsIDReader is a Reader for the GetAccountsID structure.
type GetAccountsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAccountsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAccountsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 403:
		result := NewGetAccountsIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /accounts/{id}] GetAccountsID", response, response.Code())
	}
}

// NewGetAccountsIDOK creates a GetAccountsIDOK with default headers values
func NewGetAccountsIDOK() *GetAccountsIDOK {
	return &GetAccountsIDOK{}
}

/*
GetAccountsIDOK describes a response with status code 200, with default header values.

GetAccountsIDOK get accounts Id o k
*/
type GetAccountsIDOK struct {
	AccessControlAllowHeaders string
	AccessControlAllowMethods string
	AccessControlAllowOrigin  string

	Payload *GetAccountsIDOKBody
}

// IsSuccess returns true when this get accounts Id o k response has a 2xx status code
func (o *GetAccountsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get accounts Id o k response has a 3xx status code
func (o *GetAccountsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get accounts Id o k response has a 4xx status code
func (o *GetAccountsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get accounts Id o k response has a 5xx status code
func (o *GetAccountsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get accounts Id o k response a status code equal to that given
func (o *GetAccountsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get accounts Id o k response
func (o *GetAccountsIDOK) Code() int {
	return 200
}

func (o *GetAccountsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /accounts/{id}][%d] getAccountsIdOK %s", 200, payload)
}

func (o *GetAccountsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /accounts/{id}][%d] getAccountsIdOK %s", 200, payload)
}

func (o *GetAccountsIDOK) GetPayload() *GetAccountsIDOKBody {
	return o.Payload
}

func (o *GetAccountsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Access-Control-Allow-Headers
	hdrAccessControlAllowHeaders := response.GetHeader("Access-Control-Allow-Headers")

	if hdrAccessControlAllowHeaders != "" {
		o.AccessControlAllowHeaders = hdrAccessControlAllowHeaders
	}

	// hydrates response header Access-Control-Allow-Methods
	hdrAccessControlAllowMethods := response.GetHeader("Access-Control-Allow-Methods")

	if hdrAccessControlAllowMethods != "" {
		o.AccessControlAllowMethods = hdrAccessControlAllowMethods
	}

	// hydrates response header Access-Control-Allow-Origin
	hdrAccessControlAllowOrigin := response.GetHeader("Access-Control-Allow-Origin")

	if hdrAccessControlAllowOrigin != "" {
		o.AccessControlAllowOrigin = hdrAccessControlAllowOrigin
	}

	o.Payload = new(GetAccountsIDOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAccountsIDForbidden creates a GetAccountsIDForbidden with default headers values
func NewGetAccountsIDForbidden() *GetAccountsIDForbidden {
	return &GetAccountsIDForbidden{}
}

/*
GetAccountsIDForbidden describes a response with status code 403, with default header values.

Failed to retrieve account
*/
type GetAccountsIDForbidden struct {
}

// IsSuccess returns true when this get accounts Id forbidden response has a 2xx status code
func (o *GetAccountsIDForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get accounts Id forbidden response has a 3xx status code
func (o *GetAccountsIDForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get accounts Id forbidden response has a 4xx status code
func (o *GetAccountsIDForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this get accounts Id forbidden response has a 5xx status code
func (o *GetAccountsIDForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this get accounts Id forbidden response a status code equal to that given
func (o *GetAccountsIDForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the get accounts Id forbidden response
func (o *GetAccountsIDForbidden) Code() int {
	return 403
}

func (o *GetAccountsIDForbidden) Error() string {
	return fmt.Sprintf("[GET /accounts/{id}][%d] getAccountsIdForbidden", 403)
}

func (o *GetAccountsIDForbidden) String() string {
	return fmt.Sprintf("[GET /accounts/{id}][%d] getAccountsIdForbidden", 403)
}

func (o *GetAccountsIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

/*
GetAccountsIDOKBody Account Details
swagger:model GetAccountsIDOKBody
*/
type GetAccountsIDOKBody struct {

	// Status of the Account.
	// "Ready": The account is clean and ready for lease
	// "NotReady": The account is in "dirty" state, and needs to be reset before it may be leased.
	// "Leased": The account is leased to a principal
	//
	// Enum: ["Ready","NotReady","Leased","Orphaned"]
	AccountStatus string `json:"accountStatus,omitempty"`

	// ARN for an IAM role within this AWS account. The DCE master account will assume this IAM role to execute operations within this AWS account. This IAM role is configured by the client, and must be configured with [a Trust Relationship with the DCE master account.](/https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html)
	AdminRoleArn string `json:"adminRoleArn,omitempty"`

	// Epoch timestamp, when account record was created
	CreatedOn int64 `json:"createdOn,omitempty"`

	// AWS Account ID
	ID string `json:"id,omitempty"`

	// Epoch timestamp, when account record was last modified
	LastModifiedOn int64 `json:"lastModifiedOn,omitempty"`

	// Any organization specific data pertaining to the account that needs to be persisted
	Metadata interface{} `json:"metadata,omitempty"`

	// The S3 object ETag used to apply the Principal IAM Policy within this AWS account.  This policy is created by the DCE master account, and is assumed by people with access to principalRoleArn.
	PrincipalPolicyHash string `json:"principalPolicyHash,omitempty"`

	// ARN for an IAM role within this AWS account. This role is created by the DCE master account, and may be assumed by principals to login to their AWS child account.
	PrincipalRoleArn string `json:"principalRoleArn,omitempty"`
}

// Validate validates this get accounts ID o k body
func (o *GetAccountsIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAccountStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var getAccountsIdOKBodyTypeAccountStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["Ready","NotReady","Leased","Orphaned"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		getAccountsIdOKBodyTypeAccountStatusPropEnum = append(getAccountsIdOKBodyTypeAccountStatusPropEnum, v)
	}
}

const (

	// GetAccountsIDOKBodyAccountStatusReady captures enum value "Ready"
	GetAccountsIDOKBodyAccountStatusReady string = "Ready"

	// GetAccountsIDOKBodyAccountStatusNotReady captures enum value "NotReady"
	GetAccountsIDOKBodyAccountStatusNotReady string = "NotReady"

	// GetAccountsIDOKBodyAccountStatusLeased captures enum value "Leased"
	GetAccountsIDOKBodyAccountStatusLeased string = "Leased"

	// GetAccountsIDOKBodyAccountStatusOrphaned captures enum value "Orphaned"
	GetAccountsIDOKBodyAccountStatusOrphaned string = "Orphaned"
)

// prop value enum
func (o *GetAccountsIDOKBody) validateAccountStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, getAccountsIdOKBodyTypeAccountStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (o *GetAccountsIDOKBody) validateAccountStatus(formats strfmt.Registry) error {
	if swag.IsZero(o.AccountStatus) { // not required
		return nil
	}

	// value enum
	if err := o.validateAccountStatusEnum("getAccountsIdOK"+"."+"accountStatus", "body", o.AccountStatus); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get accounts ID o k body based on context it is used
func (o *GetAccountsIDOKBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *GetAccountsIDOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *GetAccountsIDOKBody) UnmarshalBinary(b []byte) error {
	var res GetAccountsIDOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
